# Copyright(C) 2011 FUJITSU LIMITED

obj-y += fta_admin.o fta_config.o fta_config_api.o fta_lib.o fta_list.o fta_log.o fta_var.o fta_list_hash.o
obj-y += ftadrv.o ftadrv_acpu.o ftadrv_ccpu.o
ccflags-$(CONFIG_ANDROID_LOGGER) += -Iarch/arm/mach-msm

