/*----------------------------------------------------------------------------*/
// COPYRIGHT(C) FUJITSU LIMITED 2012
/*----------------------------------------------------------------------------*/

#ifndef SMB347_CHARGER_HW_H
#define SMB347_CHARGER_HW_H

//smb347 register data
//00h Charge Current
#define SMB_CHG_CURRENT_REG										0x00
//Fast Charge Current(bit7-bit5)
#define SMB_CHG_CURRENT_FAST_CHG_700mA							0x00
#define SMB_CHG_CURRENT_FAST_CHG_900mA							0x20
#define SMB_CHG_CURRENT_FAST_CHG_1200mA							0x40
#define SMB_CHG_CURRENT_FAST_CHG_1500mA							0x60
#define SMB_CHG_CURRENT_FAST_CHG_1800mA							0x80
#define SMB_CHG_CURRENT_FAST_CHG_2000mA							0xA0
#define SMB_CHG_CURRENT_FAST_CHG_2200mA							0xC0
#define SMB_CHG_CURRENT_FAST_CHG_2500mA							0xE0
#define SMB_CHG_CURRENT_FAST_CHG_MASK							0xE0
//Pre-charge Current(bit4-bit3)
#define SMB_CHG_CURRENT_PRE_CHG_100mA							0x00
#define SMB_CHG_CURRENT_PRE_CHG_150mA							0x08
#define SMB_CHG_CURRENT_PRE_CHG_200mA							0x10
#define SMB_CHG_CURRENT_PRE_CHG_250mA							0x18
#define SMB_CHG_CURRENT_PRE_CHG_MASK							0x18
//Termination Current(bit2-bit0)
#define SMB_CHG_CURRENT_TERMINATION_37_5mA						0x00
#define SMB_CHG_CURRENT_TERMINATION_50mA						0x01
#define SMB_CHG_CURRENT_TERMINATION_100mA						0x02
#define SMB_CHG_CURRENT_TERMINATION_150mA						0x03
#define SMB_CHG_CURRENT_TERMINATION_200mA						0x04
#define SMB_CHG_CURRENT_TERMINATION_250mA						0x05
#define SMB_CHG_CURRENT_TERMINATION_500mA						0x06
#define SMB_CHG_CURRENT_TERMINATION_600mA						0x07
#define SMB_CHG_CURRENT_TERMINATION_MASK						0x07

//01h Input Current Limit
#define SMB_INPUT_CURRENT_LIMIT_REG								0x01
//Max. DCIN Input Current Limit(bit7-bit4)
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_300mA				0x00
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_500mA				0x10
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_700mA				0x20
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_900mA				0x30
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_1200mA				0x40
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_1500mA				0x50
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_1800mA				0x60
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_2000mA				0x70
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_2200mA				0x80
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_2500mA				0x90
#define SMB_INPUT_CURRENT_LIMIT_DCIN_LIMIT_MASK					0xF0
//Max. USBIN HC Input Current Limit(bit3-bit0)
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_300mA				0x00
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_500mA				0x01
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_700mA				0x02
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_900mA				0x03
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_1200mA				0x04
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_1500mA				0x05
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_1800mA				0x06
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_2000mA				0x07
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_2200mA				0x08
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_2500mA				0x09
#define SMB_INPUT_CURRENT_LIMIT_USBIN_LIMIT_MASK				0x0F

//02h Various Functions
#define SMB_VARIOUS_FUNCTIONS_REG								0x02
//Input to System FET (Suspend) On/Off Control(bit7)
#define SMB_VARIOUS_FUNCTIONS_SYSTEM_FET_CTRL_SUSP				0x00
#define SMB_VARIOUS_FUNCTIONS_SYSTEM_FET_CTRL_REG				0x80
#define SMB_VARIOUS_FUNCTIONS_SYSTEM_FET_CTRL_MASK				0x80
//Reserved(bit6)
//Maximum System Voltage(bit5)
#define SMB_VARIOUS_FUNCTIONS_MAX_SYS_VOLT_01V					0x00
#define SMB_VARIOUS_FUNCTIONS_MAX_SYS_VOLT_02V					0x20
#define SMB_VARIOUS_FUNCTIONS_MAX_SYS_VOLT_MASK					0x20
//OptiCharge(bit4)
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_DISABLED					0x00
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_ENABLED					0x10
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_MASK						0x10
//OptiChargeTM Detection Threshold(bit3)
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_THRESHOLD_425V			0x00
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_THRESHOLD_450V			0x08
#define SMB_VARIOUS_FUNCTIONS_OPTICHG_THRESHOLD_MASK			0x08
//Input Source Priority (when both DCIN and USBIN are valid) - Primary Input(bit2)
#define SMB_VARIOUS_FUNCTIONS_INPUT_SRC_PRIO_DCIN				0x00
#define SMB_VARIOUS_FUNCTIONS_INPUT_SRC_PRIO_USBIN				0x04
#define SMB_VARIOUS_FUNCTIONS_INPUT_SRC_PRIO_MASK				0x04
//Battery OV(bit1)
#define SMB_VARIOUS_FUNCTIONS_BATTERY_OV_NOT_END_CHG			0x00
#define SMB_VARIOUS_FUNCTIONS_BATTERY_OV_END_CHG				0x02
#define SMB_VARIOUS_FUNCTIONS_BATTERY_OV_MASK					0x02
//VCHG Function(bit0)
#define SMB_VARIOUS_FUNCTIONS_VCHG_FUNCTION_DISABLED			0x00
#define SMB_VARIOUS_FUNCTIONS_VCHG_FUNCTION_ENABLED				0x01
#define SMB_VARIOUS_FUNCTIONS_VCHG_FUNCTION_MASK				0x01

//03h Float Voltage
#define SMB_FLOAT_VOLTAGE_REG									0x03
//Pre-charge to Fast-charge Voltage Threshold(bit7-bit6)
#define SMB_FLOAT_VOLTAGE_PRE_TO_FAST_VOLT_THRESHOLD_2_4V		0x00
#define SMB_FLOAT_VOLTAGE_PRE_TO_FAST_VOLT_THRESHOLD_2_6V		0x40
#define SMB_FLOAT_VOLTAGE_PRE_TO_FAST_VOLT_THRESHOLD_2_8V		0x80
#define SMB_FLOAT_VOLTAGE_PRE_TO_FAST_VOLT_THRESHOLD_3_0V		0xC0
#define SMB_FLOAT_VOLTAGE_PRE_TO_FAST_VOLT_MASK					0xC0
//Float Voltage(bit5-bit0)
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_50V					0x00
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_52V					0x01
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_54V					0x02
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_56V					0x03
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_58V					0x04
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_60V					0x05
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_62V					0x06
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_64V					0x07
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_66V					0x08
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_68V					0x09
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_70V					0x0A
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_72V					0x0B
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_74V					0x0C
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_76V					0x0D
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_78V					0x0E
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_80V					0x0F
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_82V					0x10
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_84V					0x11
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_86V					0x12
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_88V					0x13
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_90V					0x14
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_92V					0x15
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_94V					0x16
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_96V					0x17
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_3_98V					0x18
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_00V					0x19
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_02V					0x1A
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_04V					0x1B
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_06V					0x1C
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_08V					0x1D
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_10V					0x1E
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_12V					0x1F
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_14V					0x20
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_16V					0x21
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_18V					0x22
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_20V					0x23
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_22V					0x24
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_24V					0x25
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_26V					0x26
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_28V					0x27
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_30V					0x28
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_32V					0x29
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_34V					0x2A
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_36V					0x2B
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_38V					0x2C
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_40V					0x2D
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_42V					0x2E
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_44V					0x2F
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_46V					0x30
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_48V					0x31
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x32
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x33
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x34
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x35
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x36
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x37
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x38
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x39
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3A
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3B
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3C
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3D
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3E
//#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_4_50V					0x3F
#define SMB_FLOAT_VOLTAGE_FLOAT_VOLTAGE_MASK					0x3F

//04h Charge Control Register
#define SMB_CHG_CTRL_REG										0x04
//Automatic Recharge(bit7)
#define SMB_CHG_CTRL_AUTO_RECHG_ENABLED							0x00
#define SMB_CHG_CTRL_AUTO_RECHG_DISABLED						0x80
#define SMB_CHG_CTRL_AUTO_RECHG_MASK							0x80
//Current Termination(bit6)
#define SMB_CHG_CTRL_CURRENT_TERM_ALLOWED						0x00
#define SMB_CHG_CTRL_CURRENT_TERM_NOT_ALLOWED					0x40
#define SMB_CHG_CTRL_CURRENT_TERM_MASK							0x40
//Battery Missing Detection(bit5-bit4)
#define SMB_CHG_CTRL_BATT_MISSING_DETECT_DISABLED				0x00
#define SMB_CHG_CTRL_BATT_MISSING_DETECT_BMD_EVERY_3S			0x10
#define SMB_CHG_CTRL_BATT_MISSING_DETECT_BMD					0x20
#define SMB_CHG_CTRL_BATT_MISSING_DETECT_THERM_IO				0x30
#define SMB_CHG_CTRL_BATT_MISSING_DETECT_MASK					0x30
//Auto Recharge Threshold(bit3)
#define SMB_CHG_CTRL_AUTO_RECHG_THRESHOLD_50mV					0x00
#define SMB_CHG_CTRL_AUTO_RECHG_THRESHOLD_100mV					0x08
#define SMB_CHG_CTRL_AUTO_RECHG_THRESHOLD_MASK					0x08
//FlexCharge(bit2)
#define SMB_CHG_CTRL_FLEXCHG_DISABLED							0x00
#define SMB_CHG_CTRL_FLEXCHG_EABLED								0x04
#define SMB_CHG_CTRL_FLEXCHG_MASK								0x04
//Non-conforming (NC) Charger Detection via APSD (900msec timeout)(bit1)
#define SMB_CHG_CTRL_NC_CHARGER_DETECTION_DISABLED				0x00
#define SMB_CHG_CTRL_NC_CHARGER_DETECTION_EABLED				0x02
#define SMB_CHG_CTRL_NC_CHARGER_DETECTION_MASK					0x02
//Reserved(bit0)

//05h STAT and Timers Control Register
#define SMB_STAT_TIMER_REG										0x05
//STAT Output Polarity(bit7)
#define SMB_STAT_TIMER_OUTPUT_POLARITY_ACT_LOW					0x00
#define SMB_STAT_TIMER_OUTPUT_POLARITY_ACT_HIGH					0x80
#define SMB_STAT_TIMER_OUTPUT_POLARITY_MASK						0x80
//STAT Output Mode(bit6)
#define SMB_STAT_TIMER_OUTPUT_MODE_IND_CHG_STATE				0x00
#define SMB_STAT_TIMER_OUTPUT_MODE_USB_FAIL						0x40
#define SMB_STAT_TIMER_OUTPUT_MODE_MASK							0x40
//STAT Output Control(bit5)
#define SMB_STAT_TIMER_OUTPUT_CTRL_ENABLED						0x00
#define SMB_STAT_TIMER_OUTPUT_CTRL_DISABLED						0x20
#define SMB_STAT_TIMER_OUTPUT_CTRL_MASK							0x20
//NC Charger Input Current Limit(bit4)
#define SMB_STAT_TIMER_NC_CHARGER_CURRENT_LIMIT_100mA			0x00
#define SMB_STAT_TIMER_NC_CHARGER_CURRENT_LIMIT_HC_SETTING		0x10
#define SMB_STAT_TIMER_NC_CHARGER_CURRENT_LIMIT_MASK			0x10
//Complete Charge Timeout(bit3-bit2)
#define SMB_STAT_TIMER_COMP_CHG_TIMEOUT_382min					0x00
#define SMB_STAT_TIMER_COMP_CHG_TIMEOUT_764min					0x04
#define SMB_STAT_TIMER_COMP_CHG_TIMEOUT_1527min					0x08
#define SMB_STAT_TIMER_COMP_CHG_TIMEOUT_DISABLED				0x0c
#define SMB_STAT_TIMER_COMP_CHG_TIMEOUT_MASK					0x0c
//Pre-charge Timeout(bit1-bit0)
#define SMB_STAT_TIMER_PRE_CHG_TIMEOUT_48min					0x00
#define SMB_STAT_TIMER_PRE_CHG_TIMEOUT_95min					0x01
#define SMB_STAT_TIMER_PRE_CHG_TIMEOUT_191min					0x02
#define SMB_STAT_TIMER_PRE_CHG_TIMEOUT_DISABLED					0x03
#define SMB_STAT_TIMER_PRE_CHG_TIMEOUT_MASK						0x03

//06h Pin and Enable Control
#define SMB_PIN_ENABLE_CTRL_REG									0x06
//LED Blinking Function(bit7)
#define SMB_PIN_ENABLE_CTRL_LED_BLINK_FUNC_DISABLED				0x00
#define SMB_PIN_ENABLE_CTRL_LED_BLINK_FUNC_ENABLED				0x80
#define SMB_PIN_ENABLE_CTRL_LED_BLINK_FUNC_MASK					0x80
//Enable Pin Control(bit6-bit5)
#define SMB_PIN_ENABLE_CTRL_EN_PIN_CTRL_I2C_DISABLED_CHARGER	0x00
#define SMB_PIN_ENABLE_CTRL_EN_PIN_CTRL_I2C_ENABLES_CHARGER		0x20
#define SMB_PIN_ENABLE_CTRL_EN_PIN_CTRL_PIN_ACTIVE_HIGH			0x40
#define SMB_PIN_ENABLE_CTRL_EN_PIN_CTRL_PIN_ACTIVE_LOW			0x60
#define SMB_PIN_ENABLE_CTRL_EN_PIN_CTRL_MASK					0x60
//USB5/1/HC or USB9/1.5/HC Control(bit4)
#define SMB_PIN_ENABLE_CTRL_USB_HC_CTRL_REG_CTRL				0x00
#define SMB_PIN_ENABLE_CTRL_USB_HC_CTRL_PIN_CTRL				0x10
#define SMB_PIN_ENABLE_CTRL_USB_HC_CTRL_MASK					0x10
//USB5/1/HC Pin Behavior(bit3)
#define SMB_PIN_ENABLE_CTRL_USB_PIN_BEHAVIOR_TRI_STATE			0x00
#define SMB_PIN_ENABLE_CTRL_USB_PIN_BEHAVIOR_DUAL_STATE			0x08
#define SMB_PIN_ENABLE_CTRL_USB_PIN_BEHAVIOR_MASK				0x08
//Charger Error(bit2)
#define SMB_PIN_ENABLE_CTRL_CHG_ERROR_NOT_TRIGGER_IRQ			0x00
#define SMB_PIN_ENABLE_CTRL_CHG_ERROR_TRIGGER_IRQ				0x04
#define SMB_PIN_ENABLE_CTRL_CHG_ERROR_MASK						0x04
//APSD Done(bit1)
#define SMB_PIN_ENABLE_CTRL_APSD_DONE_NOT_TRIGGER_IRQ			0x00
#define SMB_PIN_ENABLE_CTRL_APSD_DONE_TRIGGER_IRQ				0x02
#define SMB_PIN_ENABLE_CTRL_APSD_DONE_MASK						0x02
//DCIN Input Pre-bias(bit0)
#define SMB_PIN_ENABLE_CTRL_DCIN_PRE_BIAS_DISABLED				0x00
#define SMB_PIN_ENABLE_CTRL_DCIN_PRE_BIAS_ENABLED				0x01
#define SMB_PIN_ENABLE_CTRL_DCIN_PRE_BIAS_MASK					0x01

//07h THERM and System Control A
#define SMB_THERM_SYSTEM_CTRL_A_REG								0x07
//System Tracking Voltage(bit7)
#define SMB_THERM_SYSTEM_CTRL_A_SYS_TRACKING_VOLT_100mV			0x00
#define SMB_THERM_SYSTEM_CTRL_A_SYS_TRACKING_VOLT_200mV			0x80
#define SMB_THERM_SYSTEM_CTRL_A_SYS_TRACKING_VOLT_MASK			0x80
//Minimum System Voltage(bit6)
#define SMB_THERM_SYSTEM_CTRL_A_MIN_SYS_VOLT_3_15V_3_45V		0x00
#define SMB_THERM_SYSTEM_CTRL_A_MIN_SYS_VOLT_3_60V_3_75V		0x40
#define SMB_THERM_SYSTEM_CTRL_A_MIN_SYS_VOLT_MASK				0x40
//THERM Monitor Selection(bit5)
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONI_SELECT_USBIN			0x00
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONI_SELECT_VDDCAP		0x20
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONI_SELECT_MASK			0x20
//Thermistor Monitor(bit4)
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONITOR_ENABLED			0x00
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONITOR_DISABLED			0x10
#define SMB_THERM_SYSTEM_CTRL_A_THERM_MONITOR_MASK				0x10
//Soft Cold Temp Limit Behavior(bit3-bit2)
#define SMB_THERM_SYSTEM_CTRL_A_COLD_TEMP_LIMIT_NO_RESPONSE		0x00
#define SMB_THERM_SYSTEM_CTRL_A_COLD_TEMP_LIMIT_CHG_CURRENT		0x04
#define SMB_THERM_SYSTEM_CTRL_A_COLD_TEMP_LIMIT_FLOAT_VOLT		0x08
#define SMB_THERM_SYSTEM_CTRL_A_COLD_TEMP_LIMIT_CHG_FLOAT		0x0C
#define SMB_THERM_SYSTEM_CTRL_A_COLD_TEMP_LIMIT_MASK			0x0C
//Soft Hot Temp Limit Behavior(bit1-bit0)
#define SMB_THERM_SYSTEM_CTRL_A_HOT_TEMP_LIMIT_NO_RESPONSE		0x00
#define SMB_THERM_SYSTEM_CTRL_A_HOT_TEMP_LIMIT_CHG_CURRENT		0x01
#define SMB_THERM_SYSTEM_CTRL_A_HOT_TEMP_LIMIT_FLOAT_VOLT		0x02
#define SMB_THERM_SYSTEM_CTRL_A_HOT_TEMP_LIMIT_CHG_FLOAT		0x03
#define SMB_THERM_SYSTEM_CTRL_A_HOT_TEMP_LIMIT_MASK				0x03

//08h SYSOK and USB3.0 Selection Register
#define SMB_SYSOK_USB3_REG										0x08
//SYSOK/CHG_DET_N Output Operation(bit7-bit6)
#define SMB_SYSOK_USB3_OUTPUT_OPERATION_INOK					0x00
#define SMB_SYSOK_USB3_OUTPUT_OPERATION_SYSOK_OPTION_A			0x40
#define SMB_SYSOK_USB3_OUTPUT_OPERATION_SYSOK_OPTION_B			0x80
#define SMB_SYSOK_USB3_OUTPUT_OPERATION_CHG_DET_N				0xC0
#define SMB_SYSOK_USB3_OUTPUT_OPERATION_MASK					0xC0
//USB2.0/USB3.0 Input Current Limit(bit5)
#define SMB_SYSOK_USB3_INPUT_CURRENT_LIMIT_USB2					0x00
#define SMB_SYSOK_USB3_INPUT_CURRENT_LIMIT_USB3					0x20
#define SMB_SYSOK_USB3_INPUT_CURRENT_LIMIT_MASK					0x20
//Float Voltage Compensation(bit4-bit3)
#define SMB_SYSOK_USB3_FLOAT_VOLT_COMPENSATION_VFLT_60mV		0x00
#define SMB_SYSOK_USB3_FLOAT_VOLT_COMPENSATION_VFLT_120mV		0x08
#define SMB_SYSOK_USB3_FLOAT_VOLT_COMPENSATION_VFLT_180mV		0x10
#define SMB_SYSOK_USB3_FLOAT_VOLT_COMPENSATION_VFLT_240mV		0x18
#define SMB_SYSOK_USB3_FLOAT_VOLT_COMPENSATION_MASK				0x18
//Hard Temp Limit Behavior(bit2)
#define SMB_SYSOK_USB3_HARD_TEMP_LIMIT_SUSPENDED				0x00
#define SMB_SYSOK_USB3_HARD_TEMP_LIMIT_NOT_SUSPENDED			0x04
#define SMB_SYSOK_USB3_HARD_TEMP_LIMIT_MASK						0x04
//Pre-charge to Fast-charge Threshold(bit1)
#define SMB_SYSOK_USB3_PRE_TO_FAST_THRESHOLD_ENABLED			0x00
#define SMB_SYSOK_USB3_PRE_TO_FAST_THRESHOLD_DISABLED			0x02
#define SMB_SYSOK_USB3_PRE_TO_FAST_THRESHOLD_MASK				0x02
//INOK Polarity(bit0)
#define SMB_SYSOK_USB3_INOK_POLARITY_ACTIVE_LOW					0x00
#define SMB_SYSOK_USB3_INOK_POLARITY_ACTIVE_HIGH				0x01
#define SMB_SYSOK_USB3_INOK_POLARITY_MASK						0x01

//09h Other Control A
#define SMB_OTHER_CTRL_A_REG									0x09
//OTG/ID Pin Control(bit7-bit6)
#define SMB_OTHER_CTRL_A_OTG_ID_PIN_CTRL_RID_DIS_OTG_I2C		0x00
#define SMB_OTHER_CTRL_A_OTG_ID_PIN_CTRL_RID_DIS_OTG_PIN		0x40
#define SMB_OTHER_CTRL_A_OTG_ID_PIN_CTRL_RID_ENA_OTG_I2C		0x80
#define SMB_OTHER_CTRL_A_OTG_ID_PIN_CTRL_RID_ENA_AUTO_OTG		0xC0
#define SMB_OTHER_CTRL_A_OTG_ID_PIN_CTRL_MASK					0xC0
//OTG Pin Polarity(bit5)
#define SMB_OTHER_CTRL_A_OTG_PIN_POLARITY_ACTIVE_HIGH			0x00
#define SMB_OTHER_CTRL_A_OTG_PIN_POLARITY_ACTIVE_LOW			0x20
#define SMB_OTHER_CTRL_A_OTG_PIN_POLARITY_MASK					0x20
//Minimum System Voltage(bit4)
#define SMB_OTHER_CTRL_A_MIN_SYSTEM_VOLT_3_45V_3_60V			0x00
#define SMB_OTHER_CTRL_A_MIN_SYSTEM_VOLT_3_15V_3_75V			0x10
#define SMB_OTHER_CTRL_A_MIN_SYSTEM_VOLT_MASK					0x10
//Low-Battery / SYSOK Voltage Threshold(bit3-bit0)
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_DISABLED			0x00
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_50V				0x01
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_60V				0x02
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_70V				0x03
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_80V				0x04
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_90V				0x05
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_00V				0x06
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_10V				0x07
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_70V				0x08
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_2_88V				0x09
//#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_00V			0x0A
//#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_10V			0x0B
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_25V				0x0C
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_35V				0x0D
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_46V				0x0E
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_3_58V				0x0F
#define SMB_OTHER_CTRL_A_LOW_BATT_SYSOK_VOLT_MASK				0x0F

//0Ah OTG, TLIM and THERM Control
#define SMB_OTG_TLIM_THERM_CTRL_REG								0x0A
//Charge Current Compensation(bit7-bit6)
#define SMB_OTG_TLIM_THERM_CTRL_CHG_CURRENT_COMPENSATION_250mA	0x00
#define SMB_OTG_TLIM_THERM_CTRL_CHG_CURRENT_COMPENSATION_700mA	0x40
#define SMB_OTG_TLIM_THERM_CTRL_CHG_CURRENT_COMPENSATION_900mA	0x80
#define SMB_OTG_TLIM_THERM_CTRL_CHG_CURRENT_COMPENSATION_1200mA	0xC0
#define SMB_OTG_TLIM_THERM_CTRL_CHG_CURRENT_COMPENSATION_MASK	0xC0
//Digital Thermal Regulation Temperature Threshold(bit5-bit4)
#define SMB_OTG_TLIM_THERM_CTRL_THERMAL_REGULATION_100C			0x00
#define SMB_OTG_TLIM_THERM_CTRL_THERMAL_REGULATION_110C			0x10
#define SMB_OTG_TLIM_THERM_CTRL_THERMAL_REGULATION_120C			0x20
#define SMB_OTG_TLIM_THERM_CTRL_THERMAL_REGULATION_130C			0x30
#define SMB_OTG_TLIM_THERM_CTRL_THERMAL_REGULATION_MASK			0x30
//OTG Current Limit at USBIN(bit3-bit2)
#define SMB_OTG_TLIM_THERM_CTRL_OTG_CURRENT_LIMIT_100mA			0x00
#define SMB_OTG_TLIM_THERM_CTRL_OTG_CURRENT_LIMIT_250mA			0x04
#define SMB_OTG_TLIM_THERM_CTRL_OTG_CURRENT_LIMIT_500mA			0x08
#define SMB_OTG_TLIM_THERM_CTRL_OTG_CURRENT_LIMIT_750mA			0x0C
#define SMB_OTG_TLIM_THERM_CTRL_OTG_CURRENT_LIMIT_MASK			0x0C
//OTG Battery UVLO Threshold(bit1-bit0)
#define SMB_OTG_TLIM_THERM_CTRL_OTG_BATT_UVLO_THRESHOLD_2_7V	0x00
#define SMB_OTG_TLIM_THERM_CTRL_OTG_BATT_UVLO_THRESHOLD_2_9V	0x01
#define SMB_OTG_TLIM_THERM_CTRL_OTG_BATT_UVLO_THRESHOLD_3_1V	0x02
#define SMB_OTG_TLIM_THERM_CTRL_OTG_BATT_UVLO_THRESHOLD_3_3V	0x03
#define SMB_OTG_TLIM_THERM_CTRL_OTG_BATT_UVLO_THRESHOLD_MASK	0x03

//0Bh Hard/Soft Limit Cell temperature monitor
#define SMB_LIMIT_TEMP_MONITOR_REG								0x0B
//Hard Limit Cold Temperature Alarm Trip Point(bit7-bit6)
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_COLD_TEMP_P10C		0x00
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_COLD_TEMP_P5C			0x40
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_COLD_TEMP_0C			0x80
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_COLD_TEMP_M5C			0xC0
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_COLD_TEMP_MASK		0xC0
//Hard Limit Hot Temperature Alarm Trip Point(bit5-bit4)
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_HOT_TEMP_P50C			0x00
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_HOT_TEMP_P55C			0x10
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_HOT_TEMP_P60C			0x20
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_HOT_TEMP_P65C			0x30
#define SMB_LIMIT_TEMP_MONITOR_HARD_LIMIT_HOT_TEMP_MASK			0x30
//Soft Limit Cold Temperature Alarm Trip Point(bit3-bit2)
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_COLD_TEMP_P15C		0x00
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_COLD_TEMP_P10C		0x04
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_COLD_TEMP_P5C			0x08
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_COLD_TEMP_0C			0x0C
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_COLD_TEMP_MASK		0x0C
//Soft Limit Hot Temperature Alarm Trip Point(bit1-bit0)
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_HOT_TEMP_P40C			0x00
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_HOT_TEMP_P45C			0x01
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_HOT_TEMP_P50C			0x02
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_HOT_TEMP_P55C			0x03
#define SMB_LIMIT_TEMP_MONITOR_SOFT_LIMIT_HOT_TEMP_MASK			0x03

//0Ch FAULT Interrupt Register
#define SMB_FAULT_INTERRUPT_REG									0x0C
//The following conditions assert an interrupt(bit7-bit0)
#define SMB_FAULT_INTERRUPT_TEMP_OUTSIDE_HARD_LIMIT_DETECT		0x80
#define SMB_FAULT_INTERRUPT_TEMP_OUTSIDE_SOFT_LIMIT_DETECT		0x40
#define SMB_FAULT_INTERRUPT_OTG_BATT_FAIL_UVLO_DETECT			0x20
#define SMB_FAULT_INTERRUPT_OTG_OVER_CURRENT_LIMIT_DETECT		0x10
#define SMB_FAULT_INTERRUPT_USB_OVER_VOLTAGE_DETECT				0x08
#define SMB_FAULT_INTERRUPT_USB_UNDER_VOLTAGE_DETECT			0x04
#define SMB_FAULT_INTERRUPT_AICL_COMPLETE_DETECT				0x02
#define SMB_FAULT_INTERRUPT_INTERNAL_OVER_TEMP_DETECT			0x01
#define SMB_FAULT_INTERRUPT_ALL_MASK							0xFF

//0Dh STATUS Interrupt Register
#define SMB_STATUS_INTERRUPT_REG								0x0D
//The following conditions assert an interrupt(bit7-bit0)
#define SMB_STATUS_INTERRUPT_CHG_TIMEOUT_DETECT					0x80
#define SMB_STATUS_INTERRUPT_OTG_INSERT_REMOVE_DETECT			0x40
#define SMB_STATUS_INTERRUPT_BATT_OVER_VOLTAGE_DETECT			0x20
#define SMB_STATUS_INTERRUPT_TERM_CHG_DETECT					0x10
#define SMB_STATUS_INTERRUPT_FAST_CHG_DETECT					0x08
#define SMB_STATUS_INTERRUPT_INOK_DETECT						0x04
#define SMB_STATUS_INTERRUPT_MISSING_BATT_DETECT				0x02
#define SMB_STATUS_INTERRUPT_LOW_BATT_DETECT					0x01
#define SMB_STATUS_INTERRUPT_ALL_MASK							0xFF

//0Eh I2C Bus/Slave Address (Read only)
#define SMB_BUS_SLAVE_ADDR_REG									0x0E
//I2C Slave Address(bit7-bit4)
#define SMB_BUS_SLAVE_ADDR_SLAVE_ADDRESS_MASK					0xF0
//I2C Bus Address(bit3-bit1)
#define SMB_BUS_SLAVE_ADDR_BUS_ADDRESS_MASK						0x0E
//Volatile Write Permission(bit0)
#define SMB_BUS_SLAVE_ADDR_VOLATILE_WRITE_PERM_MASK				0x01

//30h Command Register A
#define SMB_CMD_A_REG											0x30
//Volatile Write Permission(bit7)
#define SMB_CMD_A_WRITE_PERMISSION_PREVENT						0x00
#define SMB_CMD_A_WRITE_PERMISSION_ALLOW						0x80
#define SMB_CMD_A_WRITE_PERMISSION_MASK							0x80
//Fast Charge Settings(bit6)
#define SMB_CMD_A_FAST_CHG_SETTING_FORCE_PRE_CHG				0x00
#define SMB_CMD_A_FAST_CHG_SETTING_ALLOW_FAST_CHG				0x40
#define SMB_CMD_A_FAST_CHG_SETTING_MASK							0x40
//THERM/NTC Current Override(bit5)
#define SMB_CMD_A_THERM_CURR_OVERRIDE_CONFIG_SETTING			0x00
#define SMB_CMD_A_THERM_CURR_OVERRIDE_OVERRIDE_CONFIG			0x20
#define SMB_CMD_A_THERM_CURR_OVERRIDE_MASK						0x20
//OTG Enable(bit4)
#define SMB_CMD_A_OTG_ENABLE_DISABLED							0x00
#define SMB_CMD_A_OTG_ENABLE_ENABLED							0x10
#define SMB_CMD_A_OTG_ENABLE_MASK								0x10
//Battery to System Control(bit3)
#define SMB_CMD_A_BATT_SYSTEM_CTRL_INTERNAL_ALGORITHM			0x00
#define SMB_CMD_A_BATT_SYSTEM_CTRL_TURN_OFF_BATT_TO_FET			0x08
#define SMB_CMD_A_BATT_SYSTEM_CTRL_MASK							0x08
//USBIN Suspend Mode(bit2)
#define SMB_CMD_A_USBIN_SUSPEND_MODE_DISABLED					0x00
#define SMB_CMD_A_USBIN_SUSPEND_MODE_ENABLED					0x04
#define SMB_CMD_A_USBIN_SUSPEND_MODE_MASK						0x04
//Charging Enable(bit1)
#define SMB_CMD_A_CHARGING_ENABLE_ENABLED						0x00
#define SMB_CMD_A_CHARGING_ENABLE_DISABLED						0x02
#define SMB_CMD_A_CHARGING_ENABLE_MASK							0x02
//STAT Output(bit0)
#define SMB_CMD_A_STAT_OUTPUT_ENABLED							0x00
#define SMB_CMD_A_STAT_OUTPUT_DISABLED							0x01
#define SMB_CMD_A_STAT_OUTPUT_MASK								0x01

//31h Command Register B
#define SMB_CMD_B_REG											0x31
//Power On Reset(bit7)
#define SMB_CMD_B_POWER_ON_RESET_NO_EFFECT						0x00
#define SMB_CMD_B_POWER_ON_RESET_RESET							0x80
#define SMB_CMD_B_POWER_ON_RESET_MASK							0x80
//DCIN Suspend Mode(bit2)
#define SMB_CMD_B_DCIN_SUSPEND_MODE_DISABLED					0x00
#define SMB_CMD_B_DCIN_SUSPEND_MODE_ENABLED						0x04
#define SMB_CMD_B_DCIN_SUSPEND_MODE_MASK						0x04
//USB5/1 (9/1.5) Mode(bit1)
#define SMB_CMD_B_USB_5_1_MODE_USB1_OR_USB1_5					0x00
#define SMB_CMD_B_USB_5_1_MODE_USB5_OR_USB9						0x02
#define SMB_CMD_B_USB_5_1_MODE_MASK								0x02
//USB/HC Mode(bit0)
#define SMB_CMD_B_USB_HC_MODE_USB_MODE							0x00
#define SMB_CMD_B_USB_HC_MODE_HIGH_CURRENT_MODE					0x01
#define SMB_CMD_B_USB_HC_MODE_MASK								0x01

//33h Command Register C
#define SMB_CMD_C_REG											0x33
//Stop Dead Battery Timer(bit7-bit0)
#define SMB_CMD_C_REG_STOP_DEAD_BATT_TIMER_MASK					0xFF

//35h Interrupt Status Register A (Read only)
#define SMB_INTERRUPT_STATUS_A_REG								0x35
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_A_HOT_TEMP_HARD_LIMIT_IRQ			0x80
#define SMB_INTERRUPT_STATUS_A_HOT_TEMP_HARD_LIMIT_STATUS		0x40
#define SMB_INTERRUPT_STATUS_A_COLD_TEMP_HARD_LIMIT_IRQ			0x20
#define SMB_INTERRUPT_STATUS_A_COLD_TEMP_HARD_LIMIT_STATUS		0x10
#define SMB_INTERRUPT_STATUS_A_HOT_TEMP_SOFT_LIMIT_IRQ			0x08
#define SMB_INTERRUPT_STATUS_A_HOT_TEMP_SOFT_LIMIT_STATUS		0x04
#define SMB_INTERRUPT_STATUS_A_COLD_TEMP_SOFT_LIMIT_IRQ			0x02
#define SMB_INTERRUPT_STATUS_A_COLD_TEMP_SOFT_LIMIT_STATUS		0x01

//36h Interrupt Status Register B (Read only)
#define SMB_INTERRUPT_STATUS_B_REG								0x36
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_B_BATT_OVER_VOLTAGE_IRQ			0x80
#define SMB_INTERRUPT_STATUS_B_BATT_OVER_VOLTAGE_STATUS			0x40
#define SMB_INTERRUPT_STATUS_B_MISSING_BATTERY_IRQ				0x20
#define SMB_INTERRUPT_STATUS_B_MISSING_BATTERY_STATUS			0x10
#define SMB_INTERRUPT_STATUS_B_LOW_BATT_VOLTAGE_IRQ				0x08
#define SMB_INTERRUPT_STATUS_B_LOW_BATT_VOLTAGE_STATUS			0x04
#define SMB_INTERRUPT_STATUS_B_PRE_TO_FAST_CHG_BATT_VOLT_IRQ	0x02
#define SMB_INTERRUPT_STATUS_B_PRE_TO_FAST_CHG_BATT_VOLT_STATUS	0x01

//37h Interrupt Status Register C (Read only)
#define SMB_INTERRUPT_STATUS_C_REG								0x37
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_C_INTERNAL_TEMP_LIMIT_IRQ			0x80
#define SMB_INTERRUPT_STATUS_C_INTERNAL_TEMP_LIMIT_STATUS		0x40
#define SMB_INTERRUPT_STATUS_C_RECHARGE_BATT_THRESHOLD_IRQ		0x20
#define SMB_INTERRUPT_STATUS_C_RECHARGE_BATT_THRESHOLD_STATUS	0x10
#define SMB_INTERRUPT_STATUS_C_TAPER_CHARGING_MODE_IRQ			0x08
#define SMB_INTERRUPT_STATUS_C_TAPER_CHARGING_MODE_STATUS		0x04
#define SMB_INTERRUPT_STATUS_C_TERM_CHARGING_CURRENT_HIT_IRQ	0x02
#define SMB_INTERRUPT_STATUS_C_TERM_CHARGING_CURRENT_HIT_STATUS	0x01

//38h Interrupt Status Register D (Read only)
#define SMB_INTERRUPT_STATUS_D_REG								0x38
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_D_APSD_COMPLETED_IRQ				0x80
#define SMB_INTERRUPT_STATUS_D_APSD_COMPLETED_STATUS			0x40
#define SMB_INTERRUPT_STATUS_D_AICL_COMPLETE_IRQ				0x20
#define SMB_INTERRUPT_STATUS_D_AICL_COMPLETE_STATUS				0x10
#define SMB_INTERRUPT_STATUS_D_COMPLETE_CHARGE_TIMEOUT_IRQ		0x08
#define SMB_INTERRUPT_STATUS_D_COMPLETE_CHARGE_TIMEOUT_STATUS	0x04
#define SMB_INTERRUPT_STATUS_D_PRECHARGE_TIMEOUT_IRQ			0x02
#define SMB_INTERRUPT_STATUS_D_PRECHARGE_TIMEOUT_STATUS			0x01

//39h Interrupt Status Register E (Read only)
#define SMB_INTERRUPT_STATUS_E_REG								0x39
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_E_DCIN_OVER_VOLTAGE_IRQ			0x80
#define SMB_INTERRUPT_STATUS_E_DCIN_OVER_VOLTAGE_STATUS			0x40
#define SMB_INTERRUPT_STATUS_E_DCIN_UNDER_VOLTAGE_IRQ			0x20
#define SMB_INTERRUPT_STATUS_E_DCIN_UNDER_VOLTAGE_STATUS		0x10
#define SMB_INTERRUPT_STATUS_E_USBIN_OVER_VOLTAGE_IRQ			0x08
#define SMB_INTERRUPT_STATUS_E_USBIN_OVER_VOLTAGE_STATUS		0x04
#define SMB_INTERRUPT_STATUS_E_USBIN_UNDER_VOLTAGE_IRQ			0x02
#define SMB_INTERRUPT_STATUS_E_USBIN_UNDER_VOLTAGE_STATUS		0x01
//3Ah Interrupt Status Register F (Read only)
#define SMB_INTERRUPT_STATUS_F_REG								0x3A
//Interrupt (IRQ) and Status(bit7-bit0)
#define SMB_INTERRUPT_STATUS_F_OTG_OVER_CURRENT_LIMIT_IRQ		0x80
#define SMB_INTERRUPT_STATUS_F_OTG_OVER_CURRENT_LIMIT_STATUS	0x40
#define SMB_INTERRUPT_STATUS_F_OTG_BATT_UNDER_VOLTAGE_IRQ		0x20
#define SMB_INTERRUPT_STATUS_F_OTG_BATT_UNDER_VOLTAGE_STATUS	0x10
#define SMB_INTERRUPT_STATUS_F_OTG_DETECTION_IRQ				0x08
#define SMB_INTERRUPT_STATUS_F_OTG_DETECTION_STATUS				0x04
#define SMB_INTERRUPT_STATUS_F_POWER_OK_IRQ						0x02
#define SMB_INTERRUPT_STATUS_F_POWER_OK_STATUS					0x01
//3Bh Status Register A (Read only)
#define SMB_STATUS_A_REG										0x3B
//Temperature Regulation Status(bit7)
#define SMB_STATUS_A_TEMP_REGULATION_STATUS_THERMAL				0x00
#define SMB_STATUS_A_TEMP_REGULATION_STATUS_NO_THERMAL			0x80
#define SMB_STATUS_A_TEMP_REGULATION_STATUS_MASK				0x80
//THERM Soft Limit Regulation Status(bit6)
#define SMB_STATUS_A_THERM_SOFT_LIMIT_STATUS_NO_SOFT_LIMIT		0x00
#define SMB_STATUS_A_THERM_SOFT_LIMIT_STATUS_SOFT_LIMIT			0x40
#define SMB_STATUS_A_THERM_SOFT_LIMIT_STATUS_MASK				0x40
//Actual Float Voltage after Compensation(bit5-bit0)
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_50V	0x00
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_52V	0x01
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_54V	0x02
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_56V	0x03
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_58V	0x04
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_60V	0x05
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_62V	0x06
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_64V	0x07
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_66V	0x08
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_68V	0x09
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_70V	0x0A
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_72V	0x0B
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_74V	0x0C
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_76V	0x0D
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_78V	0x0E
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_80V	0x0F
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_82V	0x10
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_84V	0x11
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_86V	0x12
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_88V	0x13
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_90V	0x14
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_92V	0x15
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_94V	0x16
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_96V	0x17
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_3_98V	0x18
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_00V	0x19
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_02V	0x1A
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_04V	0x1B
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_06V	0x1C
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_08V	0x1D
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_10V	0x1E
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_12V	0x1F
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_14V	0x20
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_16V	0x21
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_18V	0x22
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_20V	0x23
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_22V	0x24
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_24V	0x25
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_26V	0x26
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_28V	0x27
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_30V	0x28
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_32V	0x29
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_34V	0x2A
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_36V	0x2B
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_38V	0x2C
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_40V	0x2D
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_42V	0x2E
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_44V	0x2F
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_46V	0x30
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_48V	0x31
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x32
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x33
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x34
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x35
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x36
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x37
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x38
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x39
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3A
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3B
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3C
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3D
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3E
//#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_COMPENSATION_4_50V	0x3F
#define SMB_STATUS_A_ACTUAL_FLOAT_VOLTAGE_MASK					0x3F

//3Ch Status Register B (Read only)
#define SMB_STATUS_B_REG										0x3C
//USB Suspend Mode(bit7)
#define SMB_STATUS_B_USB_SUSNPEND_MODE_NOT_ACTIVE				0x00
#define SMB_STATUS_B_USB_SUSNPEND_MODE_ACTIVE					0x80
#define SMB_STATUS_B_USB_SUSNPEND_MODE_MASK						0x80
//Actual Charge Current after Compensation(bit5-bit0)
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_100mA	0x00
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_150mA	0x08
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_200mA	0x10
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_250mA	0x18
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_700mA	0x20
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_900mA	0x21
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_1200mA	0x22
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_1500mA	0x23
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_1800mA	0x24
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_2000mA	0x25
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_2200mA	0x26
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_2500mA	0x27
#define SMB_STATUS_B_ACTUAL_CHARGE_CURRENT_COMPENSATION_MASK	0x3F

//3Dh Status Register C (Read only)
#define SMB_STATUS_C_REG										0x3D
//Charger Error IRQ(bit7)
#define SMB_STATUS_C_CHARGER_ERROR_IRQ_DOES_NOT_ASSERT			0x00
#define SMB_STATUS_C_CHARGER_ERROR_IRQ_ASSERTS					0x80
#define SMB_STATUS_C_CHARGER_ERROR_IRQ_MASK						0x80
//Charger Error(bit6)
#define SMB_STATUS_C_CHARGER_ERROR_NO_CHARGER_ERROR				0x00
#define SMB_STATUS_C_CHARGER_ERROR_CHARGER_ERROR				0x40
#define SMB_STATUS_C_CHARGER_ERROR_MASK							0x40
//Charging Status(bit5)
#define SMB_STATUS_C_CHARGING_STATUS1_NO_CHARGE_CYCLE			0x00
#define SMB_STATUS_C_CHARGING_STATUS1_LEAST_ONE_CHARGING_CYCLE	0x20
#define SMB_STATUS_C_CHARGING_STATUS1_MASK						0x20
//Battery Voltage Level(bit4)
#define SMB_STATUS_C_BATT_VOLTAGE_LEVEL_OVER_2_1V				0x00
#define SMB_STATUS_C_BATT_VOLTAGE_LEVEL_UNDER_2_1V				0x10
#define SMB_STATUS_C_BATT_VOLTAGE_LEVEL_MASK					0x10
//Hold-off Status(bit3)
#define SMB_STATUS_C_HOLD_OFF_STATUS_CHARGER_NOT_IN				0x00
#define SMB_STATUS_C_HOLD_OFF_STATUS_CHARGER_IN					0x08
#define SMB_STATUS_C_HOLD_OFF_STATUS_CHARGER_MASK				0x08
//Charging Status(bit2-bit1)
#define SMB_STATUS_C_CHARGING_STATUS2_NO_CHARGING				0x00
#define SMB_STATUS_C_CHARGING_STATUS2_PRE_CHARGING				0x02
#define SMB_STATUS_C_CHARGING_STATUS2_FAST_CHARGING				0x04
#define SMB_STATUS_C_CHARGING_STATUS2_TAPER_CHARGING			0x06
#define SMB_STATUS_C_CHARGING_STATUS2_MASK						0x06
//Charging Enable/Disable(bit0)
#define SMB_STATUS_C_CHARGING_ENA_DIS_CHARGER_DISABLED			0x00
#define SMB_STATUS_C_CHARGING_ENA_DIS_CHARGER_ENABLED			0x01
#define SMB_STATUS_C_CHARGING_ENA_DIS_MASK						0x01

//3Eh Status Register D (Read only)
#define SMB_STATUS_D_REG										0x3E
//RID Status(bit7)
#define SMB_STATUS_D_RID_STATUS_NOT_DONE						0x00
#define SMB_STATUS_D_RID_STATUS_DONE							0x80
#define SMB_STATUS_D_RID_STATUS_MASK							0x80
//ACA Status(bit6-bit4)
#define SMB_STATUS_D_ACA_STATUS_RID_A							0x00
#define SMB_STATUS_D_ACA_STATUS_RID_B							0x10
#define SMB_STATUS_D_ACA_STATUS_RID_C							0x20
#define SMB_STATUS_D_ACA_STATUS_RID_FLOATING					0x30
#define SMB_STATUS_D_ACA_STATUS_RID_NOT_USED					0x40
#define SMB_STATUS_D_ACA_STATUS_MASK							0x70
//APSD Status(bit3)
#define SMB_STATUS_D_APSD_STATUS_NOT_COMPLETED					0x00
#define SMB_STATUS_D_APSD_STATUS_COMPLETED						0x08
#define SMB_STATUS_D_APSD_STATUS_MASK							0x08
//APSD Results(bit2-bit0)
#define SMB_STATUS_D_APSD_RESULTS_APSD_NOT_RUN					0x00
#define SMB_STATUS_D_APSD_RESULTS_CHARGING_DOWNSTREAM_PORT		0x01
#define SMB_STATUS_D_APSD_RESULTS_DEDICATED_CHARGING_PORT		0x02
#define SMB_STATUS_D_APSD_RESULTS_OTHER_CHARGING_PORT			0x03
#define SMB_STATUS_D_APSD_RESULTS_STANDARD_DOWNSTREAM_PORT		0x04
#define SMB_STATUS_D_APSD_RESULTS_ACA_CHARGER					0x05
#define SMB_STATUS_D_APSD_RESULTS_NOT_USED						0x06
#define SMB_STATUS_D_APSD_RESULTS_MASK							0x07

//3Fh Status Register E (Read only)
#define SMB_STATUS_E_REG										0x3F
//USBIN Input(bit7)
#define SMB_STATUS_E_USBIN_INPUT_NOT_IN_USE						0x00
#define SMB_STATUS_E_USBIN_INPUT_IN_USE							0x80
#define SMB_STATUS_E_USBIN_INPUT_MASK							0x80
//USB5/1/HC or USB9/1.5/HC Mode(bit6-bit5)
#define SMB_STATUS_E_USB_MODE_HC_MODE							0x00
#define SMB_STATUS_E_USB_MODE_USB1_USB1_5_MODE					0x20
#define SMB_STATUS_E_USB_MODE_USB5_USB9_MODE					0x40
//#define SMB_STATUS_E_USB_MODE_NA								0x60
#define SMB_STATUS_E_USB_MODE_MASK								0x60
//AICL Status(bit4)
#define SMB_STATUS_E_AICL_STATUS_NOT_COMPLETED					0x00
#define SMB_STATUS_E_AICL_STATUS_COMPLETED						0x10
#define SMB_STATUS_E_AICL_STATUS_MASK							0x10
//AICL Results (Setting)(bit3-bit0)
#define SMB_STATUS_E_AICL_RESULTS_300mA							0x00
#define SMB_STATUS_E_AICL_RESULTS_500mA							0x01
#define SMB_STATUS_E_AICL_RESULTS_700mA							0x02
#define SMB_STATUS_E_AICL_RESULTS_900mA							0x03
#define SMB_STATUS_E_AICL_RESULTS_1200mA						0x04
#define SMB_STATUS_E_AICL_RESULTS_1500mA						0x05
#define SMB_STATUS_E_AICL_RESULTS_1800mA						0x06
#define SMB_STATUS_E_AICL_RESULTS_2000mA						0x07
#define SMB_STATUS_E_AICL_RESULTS_2200mA						0x08
#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x09
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0A
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0B
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0C
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0D
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0E
//#define SMB_STATUS_E_AICL_RESULTS_2500mA						0x0F
#define SMB_STATUS_E_AICL_RESULTS_MASK							0x0F


extern int fj_smb_chg_hw_get_charge_ic_error(int *ic_err, unsigned long charger_src);
extern int fj_smb_chg_hw_aicl_restart_check(void);
extern int fj_smb_chg_hw_aicl_restart(void);
extern int fj_smb_chg_hw_aicl_check(void);
extern int fj_smb_chg_hw_aicl_error_check_start(void);
extern int fj_smb_chg_hw_set_charger_enable(int charger_enable);
extern int fj_smb_chg_hw_set_voltage(int chg_voltage);
extern int fj_smb_chg_hw_set_current(int chg_current);
extern int fj_smb_chg_hw_set_vinmin(int chg_vinmin);
extern int fj_smb_chg_hw_chgic_reset(void);
extern int fj_smb_chg_hw_charge_start(unsigned int tmp_current);
extern int fj_smb_chg_hw_charge_stop(unsigned long charger_src);
extern int fj_smb_chg_hw_charge_powerpath(unsigned int tmp_current);
extern int fj_smb_chg_hw_init(struct smb347_charger *smb);

#endif /* SMB347_CHARGER_HW_H */
