snd-soc-mc_yamaha-objs := mc_asoc.o mc_asoc_dbg.o mc_asoc_parser.o \
	mcdevif.o mcdevprof.o mcdriver.o mcmachdep.o mcpacking.o mcresctrl.o mcservice.o mcdebuglog.o mccdspdrv.o

# FUJITSU:2011-11-07 change start
#obj-$(CONFIG_SND_SOC_MC_YAMAHA) += snd-soc-mc_yamaha.o
obj-$(CONFIG_WCD9310_CODEC) += snd-soc-mc_yamaha.o
# FUJITSU:2011-11-07 change end
# FUJITSU:2013-05-08 him speaker pl st
obj-$(CONFIG_WCD9310_CODEC) += speakerrecv_pl.o
# FUJITSU:2013-05-08 him speaker pl ed
