EXTRA_CFLAGS += -Idrivers/staging/android
EXTRA_CFLAGS += -Ifs

obj-$(CONFIG_CRASHDUMP)	+= crashdump.o crashdump_write.o crashdump_log_buf.o crashdump_logcat.o crashdump_backtrace_arm.o crashdump_taskinfo.o crashdump_top.o crashdump_prop.o crashdump_file.o crashdump_time.o crashdump_df.o crashdump_netcfg.o crashdump_procrank.o crashdump_librank.o crashdump_service.o
